# This is a very simple Knative Service that writes the input request to its log.

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: message-dumper
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/adamharwayne/knative-playground/cmd/dumper

---

# Subscription from the GcpPubSubSource's output Channel to the Knative Service above.

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: gcppubsub-source-sample
  namespace: default
spec:
  from:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: qux-1
  call:
    targetRef:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: message-dumper
